name: Build And Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.DEPLOY_FTP_SERVER }}
          username: ${{ secrets.DEPLOY_FTP_USERNAME }}
          password: ${{ secrets.DEPLOY_FTP_PASSWORD }}
          server-dir: /library-ui/
          local-dir: ./
          dangerous-clean-slate: true
